##
##  Makefile -- Build procedure for sample epp Apache module
##  Autogenerated via ``apxs -n epp -g''.
##

#
# minimal manual additions by lendl@nic.at
#

builddir=.
top_srcdir=/usr/local/apache2
top_builddir=/usr/local/apache2
include /usr/local/apache2/build/special.mk

version=0.0.3

FILES=mod_epp.c Makefile mod_epp.h README epptelnet.pl

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules

#   cleanup
clean:
	-rm -f mod_epp.o mod_epp.lo mod_epp.slo mod_epp.la 

#   dist
dist:
	rm -rf mod_epp.$(version)
	mkdir mod_epp.$(version)
	cp $(FILES) mod_epp.$(version)
	tar czfv mod_epp.$(version).tar.gz mod_epp.$(version)
	rm -rf mod_epp.$(version)



#   simple test
test: reload
	lynx -mime_header http://localhost/epp

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

