#!/usr/bin/perl

use CGI qw/:standard/;

$q = new CGI;

print "Content-Type: text/plain\r\n\r\n";

print <<EOH;
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0
     epp-1.0.xsd">
EOH

print "<!-- This is the generic session handler\n";
print "\tInteresting ENV parameter:\n";
print map { "\t\t$_\t$ENV{$_}\n"} (sort keys(ENV));
print "\n\n-->";


#print "\n\nCGI parameters: \n";
#@names = $q->param;
#print map { "$_\t" . $q->param($_) . "\n"} (@names);

my $cltrid = $q->param("clTRID");

$cltrid = "not-given" unless (defined($cltrid));

print <<EOM;
  <response>
    <result code="1000">
      <msg lang="en">Command completed successfully (whatever that was.)</msg>
    </result>
    <trID>
      <clTRID>$cltrid</clTRID>
    </trID>
  </response>
EOM

print "\n</epp>";

